### ISSUE TITLE
AttributeError: module 'steam' has no attribute 'SteamID'

### ISSUE THREAD

**Issue by akanora** [EvanIMK/BHOP-Server#1]
![image](https://user-images.githubusercontent.com/50810398/95130655-93eff500-0765-11eb-9b82-efdfb5c32ca3.png)

I installed all the package from requirements.txt but !record doesn't work because of line 167.

**Comment by EvanIMK** [comment]
Fixed.
https://github.com/EvanIMK/BhopTimer-Discord-Bot
